#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

AUTOMAKE_LIBDIR="$(automake --print-libdir)"
cp "${AUTOMAKE_LIBDIR}/INSTALL" ./
mkdir -p build-aux
cp "${AUTOMAKE_LIBDIR}/config.guess" build-aux/
cp "${AUTOMAKE_LIBDIR}/config.sub" build-aux/
cp "${AUTOMAKE_LIBDIR}/install-sh" build-aux/

autoreconf -fvi -Wall
